[tool.poetry]
name = "model"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
mlflow = "2.16.0"
python = "^3.11"
numpy = "*"
black = "^24.8.0"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"

